In [3]:
import pandas as pd
from matplotlib import pyplot as plt
from datetime import datetime
%matplotlib inline
import seaborn as sns
sns.set()
from matplotlib.backends.backend_pdf import PdfPages
#from mpl_toolkits.basemap import Basemap
import matplotlib.cm as cm
import matplotlib.colors as col
import matplotlib as mpl

In [ ]:
##OCEAN Scoring

##Openness to Experience
##Conscientiousness (Work Ethic)
##Extraversion
##Agreeableness
##Natural Reactions

##Each facet will have a score from 0-100
##[0,45] : Low
##[46,55] : Medium
##[56,100] : High

#Sample Score: 45    37   61   16   65
#Interpretation: O: (Low) Not very open-minded, traditionalist
#               C: (Low) Not very disciplined work ethic, prefers flexible plans, disorganized
#               E: (High) Very extraverted, outgoing, socially oriented
#               A: (Low) Hard-headed, stubborn
#               N: (High) Easily upset, prone to worry, experiences high amounts of negative emotions

In [4]:
psycho_data = pd.read_csv("../work/psychometric_info.csv")

In [58]:
psycho_data.head(42)

               employee_name  user_id   O   C   E   A   N
0           Calvin Edan Love  CEL0561  40  39  36  19  40
1    Christine Reagan Deleon  CRD0624  26  22  17  39  32
2      Jade Felicia Caldwell  JFC0557  22  16  23  40  33
3     Aquila Stewart Dejesus  ASD0577  40  48  36  14  37
4          Micah Abdul Rojas  MAR0955  36  44  23  44  25
5    Gail Rhiannon Mcconnell  GRM0868  21  25  20  13  28
6           April Alika Levy  AAL0706  37  14  28  13  25
7        Rama Vielka Clayton  RVC0232  34  20  47  38  25
8         Tasha Casey Dalton  TCD0009  44  28  44  38  23
9       Aurora Sarah Manning  ASM0575  42  25  21  45  30
10        Devin Abdul Rogers  DAR0885  43  43  44  41  25
11  Jacqueline Latifah Miles  JLM0364  35  22  15  25  37
12         Ferris Omar Barry  FOB0756  42  41  34  20  27
13          Grant Camden Gay  GCG0951  33  33  25  19  44
14          Howard Wing Yang  HWY0038  47  39  40  22  24
15        Aspen Amber Vinson  AAV0450  44  24  36  41  33
16   Colorado John Valentine  CJV0286  18  14  17  13  26
17      Tyrone Damian Garner  TDG0962  42  40  36  26  21
18  Stephanie Victoria Lyons  SVL0803  27  35  20  36  32
19      Quynn Odessa Sanford  QOS0878  18  12  20  16  29
20    Melyssa Deirdre Morgan  MDM0625  18  42  36  27  24
21         Gray Mason Fulton  GMF0738  30  40  45  20  18
22    Bianca Elizabeth Roach  BER0314  23  20  18  19  32
23     Aurelia Martina Reese  AMR0400  19  16  47  28  28
24     Yardley Cairo Elliott  YCE0983  39  21  42  30  36
25       Blaine Jelani Weeks  BJW0619  30  43  47  21  39
26   Delilah Pearl Schneider  DPS0262  20  25  20  14  32
27        TaShya Yoko Bailey  TYB0779  24  20  35  36  34
28        Melissa Ava Stuart  MAS0025  23  14  20  21  23
29         Kermit Beau Leach  KBL0260  16  15  48  16  32
30      Geoffrey Harlan Lara  GHL0460  21  37  24  17  35
31      Flynn Malcolm Gibson  FMG0527  43  38  35  38  28
32   Heather Cynthia Leonard  HCL0651  21  19  44  36  33
33    Shannon Chantale Price  SCP0130  42  18  35  32  24
34          Castor Mark Wolf  CMW0783  21  35  14  16  26
35          Ryan Kelly Frost  RKF0164  40  42  17  18  42
36            Damian Omar Le  DOL0332  32  40  41  18  24
37        Robert Samuel Chen  RSC0089  41  26  35  21  29
38        Cailin Casey Mckee  CCM0136  16  16  39  40  29
39       Nina Camille Hodges  NCH0179  17  12  40  17  25
40   Nicolas Brandon Hendrix  NBH0256  41  43  14  21  22
41      Olivia Rose Galloway  ORG0339  50  28  46  47  20

In [61]:
data = pd.DataFrame(index = range(0,len(psycho_data)),columns = ["employee_name","user_id","O","C","E","A","N"])
data.head()

  employee_name user_id    O    C    E    A    N
0           NaN     NaN  NaN  NaN  NaN  NaN  NaN
1           NaN     NaN  NaN  NaN  NaN  NaN  NaN
2           NaN     NaN  NaN  NaN  NaN  NaN  NaN
3           NaN     NaN  NaN  NaN  NaN  NaN  NaN
4           NaN     NaN  NaN  NaN  NaN  NaN  NaN

In [125]:
##Score Ranges
## 0 : Low
## 1 : Mid
## 2 : High

In [136]:
higho=0
mido = 0
lowo = 0

for i in range(0,len(psycho_data)):
    if (psycho_data.O[i] >=56):
        data.employee_name[i] = psycho_data.employee_name[i]
        data.user_id[i] = psycho_data.user_id[i]
        data.O[i] = int(2)
        higho = higho + 1
    elif ((psycho_data.O[i]>=46)&(psycho_data.O[i] < 56)):
        data.employee_name[i] = psycho_data.employee_name[i]
        data.user_id[i] = psycho_data.user_id[i]
        data.O[i] = int(1)
        mido = mido + 1
    elif (psycho_data.O[i] < 46):
        data.employee_name[i] = psycho_data.employee_name[i]
        data.user_id[i] = psycho_data.user_id[i]
        data.O[i] = int(0)
        lowo = lowo + 1

In [137]:
highc=0
midc = 0
lowc = 0

for i in range(0,len(psycho_data)):
    if (psycho_data.C[i] >=56): 
        data.C[i] = int(2)
        highc = highc + 1
    elif ((psycho_data.C[i]>=46)&(psycho_data.C[i] < 56)):
        data.C[i] = int(1)
        midc = midc + 1
    elif (psycho_data.C[i] < 46):
        data.C[i] = int(0)
        lowc = lowc + 1

In [138]:
highe=0
mide = 0
lowe = 0

for i in range(0,len(psycho_data)):
    if (psycho_data.E[i] >=56): 
        data.E[i] = int(2)
        highe = highe + 1
    elif ((psycho_data.E[i]>=46)&(psycho_data.E[i] < 56)):
        data.E[i] = int(1)
        mide = mide + 1
    elif (psycho_data.E[i] < 46):
        data.E[i] = int(0)
        lowe = lowe + 1

In [139]:
higha=0
mida = 0
lowa = 0

for i in range(0,len(psycho_data)):
    if (psycho_data.A[i] >=56): 
        data.A[i] = int(2)
        higha = higha + 1
    elif ((psycho_data.A[i]>=46)&(psycho_data.A[i] < 56)):
        data.A[i] = int(1)
        mida = mida + 1
    elif (psycho_data.A[i] < 46):
        data.A[i] = int(0)
        lowa = lowa + 1

In [140]:
highn=0
midn = 0
lown = 0

for i in range(0,len(psycho_data)):
    if (psycho_data.N[i] >=56): 
        data.N[i] = int(2)
        highn = highn + 1
    elif ((psycho_data.N[i]>=46)&(psycho_data.N[i] < 56)):
        data.N[i] = int(1)
        midn = midn + 1
    elif (psycho_data.N[i] < 46):
        data.N[i] = int(0)
        lown = lown + 1

In [141]:
data.head(42)

               employee_name  user_id  O  C  E  A  N
0           Calvin Edan Love  CEL0561  0  0  0  0  0
1    Christine Reagan Deleon  CRD0624  0  0  0  0  0
2      Jade Felicia Caldwell  JFC0557  0  0  0  0  0
3     Aquila Stewart Dejesus  ASD0577  0  1  0  0  0
4          Micah Abdul Rojas  MAR0955  0  0  0  0  0
5    Gail Rhiannon Mcconnell  GRM0868  0  0  0  0  0
6           April Alika Levy  AAL0706  0  0  0  0  0
7        Rama Vielka Clayton  RVC0232  0  0  1  0  0
8         Tasha Casey Dalton  TCD0009  0  0  0  0  0
9       Aurora Sarah Manning  ASM0575  0  0  0  0  0
10        Devin Abdul Rogers  DAR0885  0  0  0  0  0
11  Jacqueline Latifah Miles  JLM0364  0  0  0  0  0
12         Ferris Omar Barry  FOB0756  0  0  0  0  0
13          Grant Camden Gay  GCG0951  0  0  0  0  0
14          Howard Wing Yang  HWY0038  1  0  0  0  0
15        Aspen Amber Vinson  AAV0450  0  0  0  0  0
16   Colorado John Valentine  CJV0286  0  0  0  0  0
17      Tyrone Damian Garner  TDG0962  0  0  0  0  0
18  Stephanie Victoria Lyons  SVL0803  0  0  0  0  0
19      Quynn Odessa Sanford  QOS0878  0  0  0  0  0
20    Melyssa Deirdre Morgan  MDM0625  0  0  0  0  0
21         Gray Mason Fulton  GMF0738  0  0  0  0  0
22    Bianca Elizabeth Roach  BER0314  0  0  0  0  0
23     Aurelia Martina Reese  AMR0400  0  0  1  0  0
24     Yardley Cairo Elliott  YCE0983  0  0  0  0  0
25       Blaine Jelani Weeks  BJW0619  0  0  1  0  0
26   Delilah Pearl Schneider  DPS0262  0  0  0  0  0
27        TaShya Yoko Bailey  TYB0779  0  0  0  0  0
28        Melissa Ava Stuart  MAS0025  0  0  0  0  0
29         Kermit Beau Leach  KBL0260  0  0  1  0  0
30      Geoffrey Harlan Lara  GHL0460  0  0  0  0  0
31      Flynn Malcolm Gibson  FMG0527  0  0  0  0  0
32   Heather Cynthia Leonard  HCL0651  0  0  0  0  0
33    Shannon Chantale Price  SCP0130  0  0  0  0  0
34          Castor Mark Wolf  CMW0783  0  0  0  0  0
35          Ryan Kelly Frost  RKF0164  0  0  0  0  0
36            Damian Omar Le  DOL0332  0  0  0  0  0
37        Robert Samuel Chen  RSC0089  0  0  0  0  0
38        Cailin Casey Mckee  CCM0136  0  0  0  0  0
39       Nina Camille Hodges  NCH0179  0  0  0  0  0
40   Nicolas Brandon Hendrix  NBH0256  0  0  0  0  0
41      Olivia Rose Galloway  ORG0339  1  0  1  1  0

In [142]:
print(higho,highc,highe,higha,highn)

0 0 0 0 0

In [143]:
print(mido,midc,mide,mida,midn)

84 66 47 61 1

In [144]:
print(lowo,lowc,lowe,lowa,lown)

916 934 953 939 999